model = "gpt-5.3-codex"
personality = "pragmatic"
model_reasoning_effort = "xhigh"

[projects."/Users/ekajaya740/Documents/00-Inbox/LINKFOLIO/linkfolio-project"]
trust_level = "trusted"

[projects."/Users/ekajaya740/Documents/01-Project/dotfiles"]
trust_level = "trusted"

[projects."/Users/ekajaya740/Documents/00-Inbox/MIPS/work_assignments"]
trust_level = "trusted"

[projects."/Users/ekajaya740/Documents/00-Inbox/Dicoding/MBEDEJS/forum-api-starter-project"]
trust_level = "trusted"

[projects."/Users/ekajaya740/Documents/00-Inbox/lbms"]
trust_level = "trusted"

[projects."/Users/ekajaya740/Documents/00-Inbox/LINKFOLIO"]
trust_level = "trusted"

[projects."/Users/ekajaya740/Documents/00-Inbox/LINKFOLIO/apps/profill-fe"]
trust_level = "trusted"

[projects."/Users/ekajaya740/Downloads/kuis_pengolahan_data_230030556"]
trust_level = "trusted"

[projects."/Users/ekajaya740/.config/opencode"]
trust_level = "trusted"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[mcp_servers.shadcn]
command = "bunx"
args = [ "shadcn@latest", "mcp" ]
