-- Personal keybinding overrides. Loaded by ~/.config/hypr/hyprland.lua via
-- require("hypr.bindings"), after Omarchy's defaults.
--
-- Omarchy 4 already ships almost every bind the old hyprlang config defined,
-- so this file is deliberately short. Verified against
-- /usr/share/omarchy/default/hypr/bindings/*.lua -- these are already defaults:
--
--   SUPER+RETURN terminal          SUPER+SHIFT+RETURN browser
--   SUPER+SHIFT+F file manager     SUPER+ALT+SHIFT+F file manager (cwd)
--   SUPER+SHIFT+B browser          SUPER+SHIFT+ALT+B browser private
--   SUPER+SHIFT+N editor           SUPER+ALT+RETURN tmux
--   SUPER+SHIFT+M spotify          SUPER+SHIFT+ALT+M cliamp
--   SUPER+SHIFT+D docker           SUPER+SHIFT+G signal
--   SUPER+SHIFT+O obsidian         SUPER+SHIFT+W omawrite
--   SUPER+SHIFT+SLASH passwords
--   SUPER+SHIFT+A ChatGPT          SUPER+SHIFT+ALT+A Grok
--   SUPER+SHIFT+C Calendar         SUPER+SHIFT+E Email
--   SUPER+SHIFT+Y YouTube          SUPER+SHIFT+ALT+G WhatsApp
--   SUPER+SHIFT+CTRL+G Messages    SUPER+SHIFT+P Google Photos
--   SUPER+SHIFT+X X                SUPER+SHIFT+ALT+X X Post
--
-- So the only things needing a binding are the two below.

-- Activity (btop).
-- Omarchy 4 moved this to SUPER+CTRL+T; you had SUPER+SHIFT+T.
-- o.bind() replaces an existing binding for the same key, so this restores
-- your original key without an explicit unbind.
o.bind("SUPER + SHIFT + T", "Activity", { tui = "btop" })

-- IME cycle - EN -> JA (mozc) -> 中文简体 (pinyin) -> 中文繁體 (rime) -> EN.
-- Omarchy 4 has no IME bind by default (fcitx5 runs as a systemd user
-- service), so this one is genuinely new. The old bind ran `fcitx5-remote -t`,
-- which only toggles active/inactive and could never reach the other engines;
-- see ~/.local/bin/ime-cycle for why. Same shortcut, now a real 4-way picker.
o.bind("ALT + SPACE", "Cycle input method", "ime-cycle")

-- Exit Hyprland.
-- SUPER+M is free in Omarchy 4 (the stub config bound it to exit, which is why
-- it was your only working way out while the autogenerated fallback was live).
-- Omarchy 4's own exit path is SUPER+ESCAPE -> omarchy-menu system.
-- Rebound here so the key you already know keeps working.
o.bind("SUPER + M", "Exit Hyprland", "omarchy-menu toggle system")

-- Hermes agent.
-- SUPER+SHIFT+H is free in Omarchy 4 (SUPER+CTRL+H is the hardware menu, and
-- the agent picker lives on SUPER+SHIFT+CTRL+A). Launched through
-- omarchy-launch-tui so it inherits Omarchy's terminal styling, and with the
-- shared org.omarchy.agent app-id that omarchy-agent uses, so one window rule
-- covers every agent. --yolo matches how omarchy-agent starts Hermes.
o.bind("SUPER + SHIFT + H", "Hermes", "omarchy-launch-tui --app-id=org.omarchy.agent hermes --yolo")

-- Two binds from the old config are intentionally NOT ported:
--
--   SUPER+SHIFT+W -> Typora
--     Omarchy 4 binds SUPER+SHIFT+W to "Omawrite". Rebinding it to typora would
--     silently drop Omawrite. If you want Typora back, uncomment:
--     hl.unbind("SUPER + SHIFT + W")
--     o.bind("SUPER + SHIFT + W", "Typora", "uwsm-app -- typora --enable-wayland-ime")
--
--   SUPER+SHIFT+T -> btop
--     ported above, overriding Omarchy's SUPER+CTRL+T placement.
